---
version: 2.1

executors:
  # Whenever the Go version is updated here and .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.11

jobs:
  test:
    executor: golang

    steps:
    - checkout
    - run: go mod download
    - run: make promu
    - run: make style unused test build
    - run: rm -v smokeping_prober

  build:
    machine: true

    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v
    - persist_to_workspace:
        root: .
        paths:
        - .build
    - store_artifacts:
        path: .build
        destination: /build

workflows:
  version: 2
  smokeping_prober:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
